// Mocks generated by Mockito 5.4.4 from annotations
// in logbook_app_001/test/module4_savetocloud_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:logbook_app_001/features/logbook/model/log_model.dart' as _i2;
import 'package:logbook_app_001/services/mongo_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mongo_dart/mongo_dart.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLogModel_0 extends _i1.SmartFake implements _i2.LogModel {
  _FakeLogModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MongoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMongoService extends _i1.Mock implements _i3.MongoService {
  MockMongoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.LogModel>> getLogs(String? teamId) => (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [teamId],
        ),
        returnValue: _i4.Future<List<_i2.LogModel>>.value(<_i2.LogModel>[]),
      ) as _i4.Future<List<_i2.LogModel>>);

  @override
  _i4.Future<_i2.LogModel> insertLog(_i2.LogModel? log) => (super.noSuchMethod(
        Invocation.method(
          #insertLog,
          [log],
        ),
        returnValue: _i4.Future<_i2.LogModel>.value(_FakeLogModel_0(
          this,
          Invocation.method(
            #insertLog,
            [log],
          ),
        )),
      ) as _i4.Future<_i2.LogModel>);

  @override
  _i4.Future<void> updateLog(_i2.LogModel? log) => (super.noSuchMethod(
        Invocation.method(
          #updateLog,
          [log],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLog(_i5.ObjectId? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLog,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
